[package]
name = "pc-power-switch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-hyper = "0.15"
hyper-tls = "0.5"
tokio = { version = "1", features = ["full"] }